stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_enginerring:
    cmd: python src/feature_enginerring.py
    deps:
    - data/interim
    - src/feature_enginerring.py
    params:
    - feature_enginerring.max_features
    outs:
    - data/processed

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
#metrics:
#- device/metrics.json

#plots:
#- dvclive/plots/metrics:
#   x: step
#params:
#- dvclive/params.yaml
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
